version: "3.3"
services:
    ffbo.nlp_component:
        container_name: ffbo.nlp_component
        tty: true
        build:
            context: .
            dockerfile: ./Dockerfile
        image: ffbo/nlp_component:develop
        networks:
            - ffbonet
networks:
    ffbonet:
        external: true
